BoxLayoutExample:

<BoxLayoutExample>:
    orientation: "vertical"
    Button:
        text: "A"
        
        size_hint: .7, .5
        # size: "100dp", "60dp"
        # width:"100dp"
        height:"60dp"

        pos_hint: {"x": 0}
        # pos_hint: {"right": 1}
        # pos_hint: {"center_x": .5}

    Button:
        text: "B"
        size_hint: 1,2
    Label:
        text: "C"
        size_hint: 2, 1